---
ms.openlocfilehash: 75fcd5b00ea5cac218a9f7809c53b179df97825c
ms.sourcegitcommit: 94a3d151c438d34ede1d99de9eb4ebdc07ba4699
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 04/25/2019
ms.locfileid: "64488940"
---
# <a name="exceptions"></a><span data-ttu-id="03c6d-101">Wyjątki</span><span class="sxs-lookup"><span data-stu-id="03c6d-101">Exceptions</span></span>

<span data-ttu-id="03c6d-102">Wyjątki w języku C# zapewnia jednolite, ze strukturą i bezpieczny sposób obsługi zarówno w poziomie systemu, jak i w poziomie aplikacji warunków błędów.</span><span class="sxs-lookup"><span data-stu-id="03c6d-102">Exceptions in C# provide a structured, uniform, and type-safe way of handling both system level and application level error conditions.</span></span> <span data-ttu-id="03c6d-103">Mechanizm wyjątków w języku C# jest bardzo podobny do C++, za pomocą kilka istotnych różnic:</span><span class="sxs-lookup"><span data-stu-id="03c6d-103">The exception mechanism in C# is quite similar to that of C++, with a few important differences:</span></span>

*  <span data-ttu-id="03c6d-104">W języku C#, wszystkie wyjątki musi być reprezentowana przez wystąpienie typu klasy pochodne `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="03c6d-104">In C#, all exceptions must be represented by an instance of a class type derived from `System.Exception`.</span></span> <span data-ttu-id="03c6d-105">W języku C++ dowolną wartość dowolnego typu może służyć do reprezentowania wyjątek.</span><span class="sxs-lookup"><span data-stu-id="03c6d-105">In C++, any value of any type can be used to represent an exception.</span></span>
*  <span data-ttu-id="03c6d-106">W języku C# bloku finally ([instrukcjami "try"](statements.md#the-try-statement)) może służyć do pisania kodu zakończenia, który jest wykonywany w wykonywania normalnych i wyjątkowych warunków.</span><span class="sxs-lookup"><span data-stu-id="03c6d-106">In C#, a finally block ([The try statement](statements.md#the-try-statement)) can be used to write termination code that executes in both normal execution and exceptional conditions.</span></span> <span data-ttu-id="03c6d-107">Taki kod jest trudne do pisania w języku C++, bez duplikowania kodu.</span><span class="sxs-lookup"><span data-stu-id="03c6d-107">Such code is difficult to write in C++ without duplicating code.</span></span>
*  <span data-ttu-id="03c6d-108">W języku C# wyjątków na poziomie systemu, takie jak przepełnienia, dzielenie przez zero i wartość null wyłuskań mają dobrze zdefiniowane klasy wyjątków się z jest równoważny błędy na poziomie aplikacji.</span><span class="sxs-lookup"><span data-stu-id="03c6d-108">In C#, system-level exceptions such as overflow, divide-by-zero, and null dereferences have well defined exception classes and are on a par with application-level error conditions.</span></span>

## <a name="causes-of-exceptions"></a><span data-ttu-id="03c6d-109">Przyczyn wyjątków</span><span class="sxs-lookup"><span data-stu-id="03c6d-109">Causes of exceptions</span></span>

<span data-ttu-id="03c6d-110">Wyjątek może zostać wygenerowany na dwa różne sposoby.</span><span class="sxs-lookup"><span data-stu-id="03c6d-110">Exception can be thrown in two different ways.</span></span>

*  <span data-ttu-id="03c6d-111">A `throw` — instrukcja ([instrukcji "throw"](statements.md#the-throw-statement)) zgłasza wyjątek, natychmiast i bezwarunkowo.</span><span class="sxs-lookup"><span data-stu-id="03c6d-111">A `throw` statement ([The throw statement](statements.md#the-throw-statement)) throws an exception immediately and unconditionally.</span></span> <span data-ttu-id="03c6d-112">Kontrolki nigdy nie osiąga instrukcję natychmiast po `throw`.</span><span class="sxs-lookup"><span data-stu-id="03c6d-112">Control never reaches the statement immediately following the `throw`.</span></span>
*  <span data-ttu-id="03c6d-113">Niektórych wyjątkowych warunkach powstałe podczas przetwarzania instrukcji C# i wyrażeń spowodować wyjątek w pewnych okolicznościach, gdy nie można ukończyć operacji, zwykle.</span><span class="sxs-lookup"><span data-stu-id="03c6d-113">Certain exceptional conditions that arise during the processing of C# statements and expression cause an exception in certain circumstances when the operation cannot be completed normally.</span></span> <span data-ttu-id="03c6d-114">Na przykład operacja dzielenia liczby całkowitej ([operator dzielenia](expressions.md#division-operator)) zgłasza `System.DivideByZeroException` Jeżeli mianownik wynosi zero.</span><span class="sxs-lookup"><span data-stu-id="03c6d-114">For example, an integer division operation ([Division operator](expressions.md#division-operator)) throws a `System.DivideByZeroException` if the denominator is zero.</span></span> <span data-ttu-id="03c6d-115">Zobacz [wspólnej klasy wyjątków](exceptions.md#common-exception-classes) listę różnych wyjątków, które mogą wystąpić w ten sposób.</span><span class="sxs-lookup"><span data-stu-id="03c6d-115">See [Common Exception Classes](exceptions.md#common-exception-classes) for a list of the various exceptions that can occur in this way.</span></span>

## <a name="the-systemexception-class"></a><span data-ttu-id="03c6d-116">Klasy System.Exception</span><span class="sxs-lookup"><span data-stu-id="03c6d-116">The System.Exception class</span></span>

<span data-ttu-id="03c6d-117">`System.Exception` Klasa jest typem podstawowym wszystkich wyjątków.</span><span class="sxs-lookup"><span data-stu-id="03c6d-117">The `System.Exception` class is the base type of all exceptions.</span></span> <span data-ttu-id="03c6d-118">Ta klasa ma kilka istotnych właściwości, które współużytkują wszystkie wyjątki:</span><span class="sxs-lookup"><span data-stu-id="03c6d-118">This class has a few notable properties that all exceptions share:</span></span>

*  <span data-ttu-id="03c6d-119">`Message` jest to właściwość tylko do odczytu typu `string` zawierający zrozumiałą dla użytkownika opis powodu, dla wyjątku.</span><span class="sxs-lookup"><span data-stu-id="03c6d-119">`Message` is a read-only property of type `string` that contains a human-readable description of the reason for the exception.</span></span>
*  <span data-ttu-id="03c6d-120">`InnerException` jest to właściwość tylko do odczytu typu `Exception`.</span><span class="sxs-lookup"><span data-stu-id="03c6d-120">`InnerException` is a read-only property of type `Exception`.</span></span> <span data-ttu-id="03c6d-121">Jeśli wartość jest różna od null, odwołuje się do wyjątku, który spowodował bieżący wyjątek — oznacza to, bieżący wyjątek został zgłoszony w bloku catch obsługi `InnerException`.</span><span class="sxs-lookup"><span data-stu-id="03c6d-121">If its value is non-null, it refers to the exception that caused the current exception—that is, the current exception was raised in a catch block handling the `InnerException`.</span></span> <span data-ttu-id="03c6d-122">W przeciwnym razie jego wartość wynosi null, wskazujący, że ten wyjątek nie zostało spowodowane przez inny wyjątek.</span><span class="sxs-lookup"><span data-stu-id="03c6d-122">Otherwise, its value is null, indicating that this exception was not caused by another exception.</span></span> <span data-ttu-id="03c6d-123">Liczba obiektów wyjątków połączonych ze sobą w ten sposób może być dowolną.</span><span class="sxs-lookup"><span data-stu-id="03c6d-123">The number of exception objects chained together in this manner can be arbitrary.</span></span>

<span data-ttu-id="03c6d-124">Wartości tych właściwości można określić w wywołaniach do konstruktora wystąpienia dla `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="03c6d-124">The value of these properties can be specified in calls to the instance constructor for `System.Exception`.</span></span>

## <a name="how-exceptions-are-handled"></a><span data-ttu-id="03c6d-125">Sposób obsługi wyjątków</span><span class="sxs-lookup"><span data-stu-id="03c6d-125">How exceptions are handled</span></span>

<span data-ttu-id="03c6d-126">Wyjątki są obsługiwane przez `try` — instrukcja ([instrukcjami "try"](statements.md#the-try-statement)).</span><span class="sxs-lookup"><span data-stu-id="03c6d-126">Exceptions are handled by a `try` statement ([The try statement](statements.md#the-try-statement)).</span></span>

<span data-ttu-id="03c6d-127">Gdy wystąpi wyjątek, system wyszukuje najbliższej `catch` klauzula, która może obsłużyć wyjątek, zgodnie z ustaleniami typu run-time wyjątku.</span><span class="sxs-lookup"><span data-stu-id="03c6d-127">When an exception occurs, the system searches for the nearest `catch` clause that can handle the exception, as determined by the run-time type of the exception.</span></span> <span data-ttu-id="03c6d-128">Po pierwsze bieżącej metody jest wyszukiwana w załączonym leksykalnie `try` instrukcji i klauzule powiązaną instrukcją catch instrukcji try są uwzględniane w kolejności.</span><span class="sxs-lookup"><span data-stu-id="03c6d-128">First, the current method is searched for a lexically enclosing `try` statement, and the associated catch clauses of the try statement are considered in order.</span></span> <span data-ttu-id="03c6d-129">Jeśli ono zawiedzie, połączenie jest wyszukiwane na leksykalnie otaczającej metody, która wywołała bieżącą metodę `try` instrukcję, która zawiera punkt wywołania do bieżącej metody.</span><span class="sxs-lookup"><span data-stu-id="03c6d-129">If that fails, the method that called the current method is searched for a lexically enclosing `try` statement that encloses the point of the call to the current method.</span></span> <span data-ttu-id="03c6d-130">To wyszukiwanie jest kontynuowane do `catch` klauzuli zostanie znaleziony, które może obsłużyć bieżący wyjątek za pomocą nazw, klasy wyjątku, który jest w tej samej klasie lub jako klasa bazowa typów w czasie wykonywania wyjątek.</span><span class="sxs-lookup"><span data-stu-id="03c6d-130">This search continues until a `catch` clause is found that can handle the current exception, by naming an exception class that is of the same class, or a base class, of the run-time type of the exception being thrown.</span></span> <span data-ttu-id="03c6d-131">A `catch` klauzula, która nie nazwa klasy wyjątków może obsługiwać wszystkie wyjątki.</span><span class="sxs-lookup"><span data-stu-id="03c6d-131">A `catch` clause that doesn't name an exception class can handle any exception.</span></span>

<span data-ttu-id="03c6d-132">Po znalezieniu pasującego klauzuli catch system przygotowuje kontrola jest przekazywana do pierwszej instrukcji klauzuli "catch".</span><span class="sxs-lookup"><span data-stu-id="03c6d-132">Once a matching catch clause is found, the system prepares to transfer control to the first statement of the catch clause.</span></span> <span data-ttu-id="03c6d-133">Przed rozpoczęciem wykonywania klauzuli "catch", system najpierw wykonuje, w kolejności, dowolny `finally` zagnieżdżonych klauzul skojarzonych z instrukcji try więcej, niż ten, który Przechwycono wyjątek.</span><span class="sxs-lookup"><span data-stu-id="03c6d-133">Before execution of the catch clause begins, the system first executes, in order, any `finally` clauses that were associated with try statements more nested that than the one that caught the exception.</span></span>

<span data-ttu-id="03c6d-134">Jeśli nie pasującego klauzuli "catch" zostanie znaleziony, wystąpi jedno z następujących czynności:</span><span class="sxs-lookup"><span data-stu-id="03c6d-134">If no matching catch clause is found, one of two things occurs:</span></span>

*  <span data-ttu-id="03c6d-135">Jeśli wyszukiwanie pasujące klauzuli catch osiągnie Konstruktor statyczny ([konstruktorów statycznych](classes.md#static-constructors)) lub statycznego inicjatora pola użycie, a następnie `System.TypeInitializationException` jest generowany w momencie, który wyzwolił wywołanie konstruktora statycznego.</span><span class="sxs-lookup"><span data-stu-id="03c6d-135">If the search for a matching catch clause reaches a static constructor ([Static constructors](classes.md#static-constructors)) or static field initializer, then a `System.TypeInitializationException` is thrown at the point that triggered the invocation of the static constructor.</span></span> <span data-ttu-id="03c6d-136">Wewnętrzny wyjątek `System.TypeInitializationException` zawiera wyjątek, który pierwotnie został zgłoszony.</span><span class="sxs-lookup"><span data-stu-id="03c6d-136">The inner exception of the `System.TypeInitializationException` contains the exception that was originally thrown.</span></span>
*  <span data-ttu-id="03c6d-137">Jeśli szukania klauzule catch osiągnie kod, który początkowo uruchomiony wątek, wykonywanie wątku jest zakończony.</span><span class="sxs-lookup"><span data-stu-id="03c6d-137">If the search for matching catch clauses reaches the code that initially started the thread, then execution of the thread is terminated.</span></span> <span data-ttu-id="03c6d-138">Wpływ stracą jest zdefiniowane w implementacji.</span><span class="sxs-lookup"><span data-stu-id="03c6d-138">The impact of such termination is implementation-defined.</span></span>

<span data-ttu-id="03c6d-139">Wyjątki, które występują podczas wykonywania destruktor są warte szczególnej uwagi.</span><span class="sxs-lookup"><span data-stu-id="03c6d-139">Exceptions that occur during destructor execution are worth special mention.</span></span> <span data-ttu-id="03c6d-140">Jeśli wystąpi wyjątek podczas wykonywania destruktor, ten wyjątek nie zostanie przechwycony, wykonanie tego destruktor zostanie zakończony i nosi nazwę destruktor klasy podstawowej (jeśli istnieje).</span><span class="sxs-lookup"><span data-stu-id="03c6d-140">If an exception occurs during destructor execution, and that exception is not caught, then the execution of that destructor is terminated and the destructor of the base class (if any) is called.</span></span> <span data-ttu-id="03c6d-141">Jeśli nie ma klasy podstawowej (podobnie jak w przypadku właściwości `object` typu) lub jeśli nie ma żadnych destruktor klasy podstawowej, wówczas wyjątek jest odrzucany.</span><span class="sxs-lookup"><span data-stu-id="03c6d-141">If there is no base class (as in the case of the `object` type) or if there is no base class destructor, then the exception is discarded.</span></span>

## <a name="common-exception-classes"></a><span data-ttu-id="03c6d-142">Wspólne klasy wyjątków</span><span class="sxs-lookup"><span data-stu-id="03c6d-142">Common Exception Classes</span></span>

<span data-ttu-id="03c6d-143">Następujące wyjątki są zgłaszane przez niektóre operacje języka C#.</span><span class="sxs-lookup"><span data-stu-id="03c6d-143">The following exceptions are thrown by certain C# operations.</span></span>

|                                      |                |
|--------------------------------------|----------------|
| `System.ArithmeticException`         | <span data-ttu-id="03c6d-144">Klasa bazowa dla wyjątków, które występują podczas operacje arytmetyczne, takie jak `System.DivideByZeroException` i `System.OverflowException`.</span><span class="sxs-lookup"><span data-stu-id="03c6d-144">A base class for exceptions that occur during arithmetic operations, such as `System.DivideByZeroException` and `System.OverflowException`.</span></span> | 
| `System.ArrayTypeMismatchException`  | <span data-ttu-id="03c6d-145">Element zgłaszany, gdy magazyn do tablicy nie powiedzie się, ponieważ rzeczywisty typ elementu przechowywane jest niezgodna z rzeczywisty typ tablicy.</span><span class="sxs-lookup"><span data-stu-id="03c6d-145">Thrown when a store into an array fails because the actual type of the stored element is incompatible with the actual type of the array.</span></span> | 
| `System.DivideByZeroException`       | <span data-ttu-id="03c6d-146">Element zgłaszany, gdy wystąpi próba dzielenia wartości całkowitej przez zero.</span><span class="sxs-lookup"><span data-stu-id="03c6d-146">Thrown when an attempt to divide an integral value by zero occurs.</span></span> | 
| `System.IndexOutOfRangeException`    | <span data-ttu-id="03c6d-147">Element zgłaszany, gdy próba indeksu tablicy przy użyciu indeksu, który jest mniejsza od zera lub poza granice tablicy.</span><span class="sxs-lookup"><span data-stu-id="03c6d-147">Thrown when an attempt to index an array via an index that is less than zero or outside the bounds of the array.</span></span> | 
| `System.InvalidCastException`        | <span data-ttu-id="03c6d-148">Element zgłaszany, gdy konwersja jawna z typem bazowym lub interfejsem do typu pochodnego nie powiedzie się w czasie wykonywania.</span><span class="sxs-lookup"><span data-stu-id="03c6d-148">Thrown when an explicit conversion from a base type or interface to a derived type fails at run time.</span></span> | 
| `System.NullReferenceException`      | <span data-ttu-id="03c6d-149">Generowany, gdy `null` odwołanie jest używane w sposób, który powoduje, że przywoływany obiekt jest wymagane.</span><span class="sxs-lookup"><span data-stu-id="03c6d-149">Thrown when a `null` reference is used in a way that causes the referenced object to be required.</span></span> | 
| `System.OutOfMemoryException`        | <span data-ttu-id="03c6d-150">Zgłaszany, gdy próba przydzielenia pamięci (za pośrednictwem `new`) kończy się niepowodzeniem.</span><span class="sxs-lookup"><span data-stu-id="03c6d-150">Thrown when an attempt to allocate memory (via `new`) fails.</span></span> | 
| `System.OverflowException`           | <span data-ttu-id="03c6d-151">Zgłaszany, gdy operacja arytmetyczna w `checked` przepełnienia kontekstu.</span><span class="sxs-lookup"><span data-stu-id="03c6d-151">Thrown when an arithmetic operation in a `checked` context overflows.</span></span> | 
| `System.StackOverflowException`      | <span data-ttu-id="03c6d-152">Zgłaszany, gdy stos wykonywania wyczerpaniu przez zbyt wiele wywołań metod oczekujące; Zazwyczaj niepokoju bardzo szczegółowe lub niepowiązane rekursji.</span><span class="sxs-lookup"><span data-stu-id="03c6d-152">Thrown when the execution stack is exhausted by having too many pending method calls; typically indicative of very deep or unbounded recursion.</span></span> | 
| `System.TypeInitializationException` | <span data-ttu-id="03c6d-153">Zgłaszany, gdy statyczny Konstruktor zgłasza wyjątek, a nie `catch` klauzul istnieje, aby przechwytywać je.</span><span class="sxs-lookup"><span data-stu-id="03c6d-153">Thrown when a static constructor throws an exception, and no `catch` clauses exists to catch it.</span></span> | 
